/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f407xx.h"
#include "gpio.h"
#include "spi.h"
#include "rcc.h"

void SPI_GPIOInits(void);
void SPI_Inits(void);
void delay(uint32_t count);

extern uint32_t RCC_OscConfig(RCC_OscInitTypeDef *RCC_OscInitStruct);
extern uint32_t RCC_ClockConfig(RCC_ClkInitTypeDef *RCC_ClkInitStruct, uint32_t FlashLatency);

extern uint32_t SystemCoreClock;

int main(void)
{
    uint32_t status  = 0;

    SPI_GPIOInits();
    SPI_Inits();

    RCC_OscInitTypeDef OscInit = {0};

    // Örnek : HSE'yi aç ve PLL'i kullan
    OscInit.OscillatorType = RCC_OSCILLATORTYPE_HSE | RCC_OSCILLATORTYPE_PLL;
    OscInit.HSEState = RCC_HSE_ON;

    // PLL yapılandırması
    OscInit.PLL.PLLState = RCC_PLL_ON;
    OscInit.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    OscInit.PLL.PLLM = 8;   // Örn: 8MHz / 8 = 1MHz VCO girişi
    OscInit.PLL.PLLN = 336; // Örn: 1MHz * 336 = 336MHz VCO çıkışı
    OscInit.PLL.PLLP = 2;   // Örn: 336MHz / 2 = 168MHz SYSCLK
    OscInit.PLL.PLLQ = 7;   // USB, SDIO, RNG için 336 MHz / 7 = 48MHz

    status = RCC_OscConfig(&OscInit);
    if(status != 0)
    {
        while(1);
    }

    // Saat ve Bölücüler yapılandırması
    RCC_ClkInitTypeDef ClkInit = {0};

    ClkInit.ClockType = RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK |RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    ClkInit.SYSCLKSource = RCC_SYSCLKSOURCE_PLL;
    ClkInit.AHBCLKDivider = RCC_AHB_DIV_1;      // HCLK = SYSCLK / 1 = 168MHz
    ClkInit.APB1CLKDivider = RCC_APB_DIV_4;     // PCLK1 = HCLK / 4 = 42MHz
    ClkInit.APB2CLKDivider = RCC_APB_DIV_2;     // PCLK2 = HCLK / 2 = 84MHz

    status = RCC_ClockConfig(&ClkInit, FLASH_LATENCY_3);

    if(status != 0)
    {
        while(1);
    }


    
    char data[] = "Hello World";
    /* Loop forever */
	while(1)
    {
        SPI_SendData(SPI1, (uint8_t*)data, strlen(data));
        delay(500000);
    }
}



void delay(uint32_t count)
{
    while(count--);
}
